services:

  api-gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - otel-collector
    environment:
      # --- Agent Configuration ---
      - JAVA_TOOL_OPTIONS=-javaagent:pyroscope.jar -javaagent:opentelemetry-javaagent.jar
      - OTEL_SERVICE_NAME=gateway
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_METRICS_EXPORTER=otlp
      - PYROSCOPE_APPLICATION_NAME=gateway
      - PYROSCOPE_SERVER_ADDRESS=http://pyroscope:4040
      # --- Application Configuration ---
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://localhost:8761/service-registry/
      # ✅ Pass the correct Loki URL to the application
      - LOKI_URL=http://loki:3100/loki/api/v1/push
    networks:
      - app-network

  # --- Observability Stack ---
  otel-collector:
    # ... (no changes needed here)
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - tempo
      - prometheus
    networks:
      - app-network

  prometheus:
    # ... (no changes needed here)
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - app-network

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100" # This port is for Grafana to connect AND for the app to send logs
    networks:
      - app-network

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    ports:
      # ✅ Expose the query port (3100) and remap it to 3200 on the host
      # to avoid conflict with Loki's host port. OTLP port is internal.
      - "3200:3100" 
    networks:
      - app-network

  pyroscope:
    # ... (no changes needed here)
    image: grafana/pyroscope:latest
    container_name: pyroscope
    ports:
      - "4040:4040"
    networks:
      - app-network

  grafana:
    # ... (no changes needed here)
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    depends_on:
      - prometheus
      - loki
      - tempo
      - pyroscope
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
